(define-module (laura packages dee)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix build-system cargo)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages crypto)
  #:use-module (gnu packages crates-io)
  #:use-module (laura packages rust-common)
)

(define-public drand-rs
  (package
    (name "drand-rs")
    (version "0.0.16")
    (source
     (origin
       (method url-fetch)
       (uri (crate-uri "dee" version))
       (file-name (string-append name "-" version ".tar.gz"))
       (sha256
        (base32 "05bar6jgic8idsf6rs6w0fxx0c8dzll7nbz99nj4921d4psf579r"))))
    (build-system cargo-build-system)
    (arguments
     `(#:cargo-inputs (("rust-anyhow" ,rust-anyhow-1)
                       ("rust-clap" ,rust-clap-4)
                       ("rust-clap" ,rust-clap-4)
                       ("rust-clap-verbosity-flag" ,rust-clap-verbosity-flag-2)
                       ("rust-clap-verbosity-flag" ,rust-clap-verbosity-flag-2)
                       ("rust-clap-complete" ,rust-clap-complete-4)
                       ("rust-clap-mangen" ,rust-clap-mangen-0.2)
                       ("rust-colored" ,rust-colored-2)
                       ("rust-confy" ,rust-confy-0.6)
                       ("rust-drand-core" ,rust-drand-core-0.0.16)
                       ("rust-env-logger" ,rust-env-logger-0.10)
                       ("rust-flate2" ,rust-flate2-1)
                       ("rust-hex" ,rust-hex-0.4)
                       ("rust-log" ,rust-log-0.4)
                       ("rust-serde" ,rust-serde-1)
                       ("rust-serde-json" ,rust-serde-json-1)
                       ("rust-time" ,rust-time-0.3)
                       ("rust-tlock-age" ,rust-tlock-age-0.0.5)
                       ("rust-tlock-age" ,rust-tlock-age-0.0.3))))
    (home-page "https://github.com/thibmeu/drand-rs")
    (synopsis "An cli for drand, with support for timelock encryption")
    (description
     "This package provides An cli for drand, with support for timelock encryption.")
    (license license:expat)))
